#!/usr/bin/env bash
# d-aws - Run AWS CLI from Docker

set -o errexit
set -o nounset
set -o pipefail

# enable interruption signal handling
trap - INT TERM

docker run --rm \
	-t $(tty &>/dev/null && echo "-i") \
    -v "$HOME/.aws:/root/.aws" \
	-v "$(pwd):/project" \
	mesosphere/aws-cli \
	"$@"
