#!/usr/bin/env sh
# docker-run-1password - Run 1Password CLI using Docker

# not working:
#docker run --privileged --cgroupns=host --network=host --ipc=host --pid=host --userns=host --uts=host --cap-add=IPC_OWNER --rm -it -v /tmp:/tmp -v /var/run/dbus:/var/run/dbus -v /dev/shm:/dev/shm -v /etc/passwd:/etc/passwd:ro -v /etc/shadow:/etc/shadow:ro -v /etc/group:/etc/group:ro -v $HOME:$HOME -e DISPLAY -u `id -u`:`id -g` my-1password-op 1password --disable-gpu --log trace
#docker run --privileged --cgroupns=host --network=host --ipc=host --pid=host --userns=host --uts=host --cap-add=IPC_OWNER --rm -it -v /tmp:/tmp -v /var/run/dbus:/var/run/dbus -v /dev/shm:/dev/shm -v /etc/passwd:/etc/passwd:ro -v /etc/shadow:/etc/shadow:ro -v /etc/group:/etc/group:ro -v $HOME:/home/psypete -e DISPLAY -u `id -u`:`id -g` my-1password-op 1password --disable-gpu

# close:
#docker run --network=host --rm -it -v /var/run/dbus:/var/run/dbus -v /dev/shm:/dev/shm -v /tmp:/tmp -v /etc/passwd:/etc/passwd:ro -v /etc/shadow:/etc/shadow:ro -v /etc/group:/etc/group:ro -v $HOME:$HOME -p 2222:2222 my-1password-op

# working:
#docker run --privileged --network=host --rm -it -v /etc/passwd:/etc/passwd:ro -v /etc/shadow:/etc/shadow:ro -v /etc/group:/etc/group:ro -v $HOME:$HOME -e DISPLAY -u `id -u`:`id -g` my-1password-op 1password --disable-gpu
#docker run --privileged --cgroupns=host --network=host --ipc=host --pid=host --userns=host --uts=host --rm -it -v /tmp:/tmp -v /var/run/dbus:/var/run/dbus -v /dev/shm:/dev/shm -v /etc/passwd:/etc/passwd:ro -v /etc/shadow:/etc/shadow:ro -v /etc/group:/etc/group:ro -v $HOME:$HOME -e DISPLAY -u `id -u`:`id -g` my-1password-op 1password --disable-gpu --no-sandbox --no-zygote --log trace
#docker run --privileged --cgroupns=host --network=host --ipc=host --pid=host --userns=host --uts=host --rm -it -v /tmp:/tmp -v /var/run/dbus:/var/run/dbus -v /dev/shm:/dev/shm -v /etc/passwd:/etc/passwd:ro -v /etc/shadow:/etc/shadow:ro -v /etc/group:/etc/group:ro -v $HOME:$HOME -e DISPLAY -u `id -u`:`id -g` my-1password-op 1password --disable-gpu --log trace


#        --cgroupns=host \
#        --userns=host \
#        --uts=host \
#        --ipc=host \
#

docker run \
        --name my-1password-op \
        --privileged \
        --rm \
        --network=host \
        --pid=host \
        -v /tmp:/tmp \
        -v /etc/passwd:/etc/passwd:ro \
        -v /etc/shadow:/etc/shadow:ro \
        -v /etc/group:/etc/group:ro \
        -v /etc/localtime:/etc/localtime:ro \
        -v /etc/zoneinfo/US/Eastern:/etc/zoneinfo/US/Eastern:ro \
        -v $HOME:$HOME \
        -e DISPLAY \
        -u `id -u`:`id -g` \
        my-1password-op \
            1password --disable-gpu --log debug
